language: c
sudo: required
dist: trusty

env:
  - LUA="lua5.1" LUAC="luac5.1"

install:
  - sudo apt-get update -qq # required since the travis switch to GCE
  - sudo apt-get install $LUA luarocks
  - sudo luarocks install luaunit
  - sudo luarocks install mockagne
  - sudo luarocks install luabitop

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - $LUA core.lua
  - $LUA databases.lua

notifications:
  email:
    on_failure: always
    on_success: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9437daaf311c6276dc3
    on_success: change
    on_failure: always
