sudo: false

env:
  - LUA="lua5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - lua5.1
      - luarocks
      - liblua5.1-bitop0

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luaunit 2.1
  - luarocks install --local mockagne 1.0

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - $LUA core.lua
  - $LUA databases.lua

deploy:
  provider: script
  script: curl -XPOST -sS "https://www.wowace-or-what.com/api/projects/72228/package?token=$WOWACE_API_TOKEN" -d '{"ping":1}'
  on:
    repo: AdiAddons/LibPlayerSpells-1.0
    all_branches: true
    condition: '"$TRAVIS_BRANCH" = master || -n "$TRAVIS_TAG"'

notifications:
  email:
    on_failure: always
    on_success: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9437daaf311c6276dc3
    on_success: change
    on_failure: always

cache:
  apt: true
  directories:
    - $HOME/.luarocks
